ymrl/a11y-visualizer

src/content/dom/collectElements.ts
=> :bug: fix tips position in dialogs and popovers

src/content/components/MetaInfo.tsx, src/content/dom/collectElements.ts, src/content/dom/tips/ariaHiddenTips.test.ts, src/content/dom/tips/buttonTips.test.ts, src/content/dom/tips/buttonTips.ts, src/content/dom/tips/formTips.test.ts, src/content/dom/tips/formTips.ts, src/content/dom/tips/headingTips.test.ts, src/content/dom/tips/headingTips.ts, src/content/dom/tips/imageTips.test.ts, src/content/dom/tips/imageTips.ts, src/content/dom/tips/linkTips.test.ts, src/content/dom/tips/linkTips.ts
=> :bug: Fix overlapped name

src/content/dom/getClosestByRoles.test.ts, src/content/dom/getClosestByRoles.ts, src/content/dom/getKnownRole.test.ts, src/content/dom/getKnownRole.ts, src/content/dom/index.ts, src/content/dom/tips/imageTips.test.ts, src/content/dom/tips/imageTips.ts, src/test/TestIframe.tsx, src/test/categories/Image.tsx, src/test/iframe.html, src/test/iframe.tsx
=> :sparkles: not show "noName" error if image is descendant of button or link

src/i18n/index.ts, src/i18n/ko.json, src/useLang.ts
Thanks to [purplemiyazawa](https://twitter.com/purplemiyazawa), Added Korean Language Support
=> :+1: add Korean Language support

src/background.ts, src/components/Checkbox.tsx, src/components/SettingsEditor.tsx, src/content/Root.tsx, src/content/injectRoot.tsx, src/enabled.ts, src/i18n/en.json, src/i18n/ja.json, src/i18n/ko.json, src/options/OptionsPage.tsx, src/popup/Popup.tsx, src/settings/types.ts
=> :+1: add "Enable Accessiblity Visualizer" Checkbox

src/content/Root.tsx, src/content/hooks/useLiveRegion.ts
=> :+1: add ctrl-key to stop live-region announcement

src/content/injectRoot.tsx
https://github.com/ymrl/a11y-visualizer/issues/14#issuecomment-2119126477
=> :+1: add aria-hidden="true" to visualizer root element

src/content/hooks/useLiveRegion.ts
=> :+1: add focusin event to clear announcement

src/components/SettingsEditor.tsx, src/content/Root.tsx, src/content/components/ElementInfo.css, src/content/components/ElementInfo.tsx, src/content/components/Tip.css, src/content/components/Tip.tsx, src/content/dom/collectElements.ts, src/content/dom/tips/sectionTips.test.ts, src/content/dom/tips/sectionTips.ts, src/content/injectRoot.tsx, src/content/types.ts, src/i18n/en.json, src/i18n/ja.json, src/settings/constatns.ts, src/settings/types.ts
=> :+1: show section (landmark) tips

src/content/components/ElementInfo.css, src/content/components/ElementInfo.tsx, src/content/dom/collectElements.ts, src/content/dom/tips/formTips.ts, src/content/types.ts
=> :+1: show fieldset

src/components/Checkbox.tsx, src/popup/Popup.tsx
=> :+1: enlarge enable checkbox

src/content/Root.tsx, src/content/index.ts, src/content/injectRoot.tsx, src/settings/types.ts
=> :bug: Remove root element when disabled

src/content/components/Tip.css, src/content/components/Tip.tsx, src/content/components/vars.css, src/content/dom/tips/globalTips.test.ts, src/content/dom/tips/globalTips.ts, src/content/types.ts, src/i18n/en.json, src/i18n/ja.json
close #106 
WAI-ARIA仕様書を読むと、「ステート」として定義されている属性の種類はあまり多くないので、全部表示することにした
=> :+1: add ariaStatus tip

src/components/SettingsEditor.tsx, src/content/components/ElementInfo.tsx, src/content/components/Tip.css, src/i18n/en.json, src/i18n/ja.json, src/settings/constatns.ts, src/settings/types.ts
=> :+1: add settings to change tip font size

src/content/dom/tips/globalTips.test.ts, src/content/dom/tips/globalTips.ts, src/i18n/en.json, src/i18n/ja.json, src/test/categories/FormControl.tsx
=> :+1: add aria-checked/disabled on normal checked/disabled

src/content/dom/getClosestByRoles.test.ts, src/content/dom/getClosestByRoles.ts, src/content/dom/index.ts, src/content/dom/isPresentationalChildren.test.ts, src/content/dom/isPresentationalChildren.ts, src/content/dom/tips/imageTips.test.ts, src/content/dom/tips/imageTips.ts, src/i18n/en.json, src/i18n/ja.json, src/test/categories/Button.tsx, src/test/categories/Image.tsx
=> :+1: add "mayBeSkipped" tip for svg element

src/content/dom/tips/buttonTips.test.ts, src/content/dom/tips/buttonTips.ts, src/content/dom/tips/globalTips.test.ts, src/content/dom/tips/globalTips.ts, src/test/categories/Button.tsx
=> :+1: add summary element to button tip target

src/content/dom/tips/buttonTips.test.ts, src/content/dom/tips/buttonTips.ts
=> :+1: add role="menuitem" to button tip target

src/chrome/localStorage.ts, src/components/SettingsEditor.tsx, src/content/components/Announcements.tsx, src/i18n/en.json, src/i18n/ja.json, src/options/OptionsPage.tsx, src/popup/Popup.tsx, src/settings/constatns.ts, src/settings/storage.ts, src/settings/types.ts
- Add font size settings for live region
- Add reset to default feature to options page
- Change Defaults
- Button tip to true
- Tip opacity to 30
=> :+1: add live region font settings, reset settings and change defaults

manifest.json, src/content/index.ts, vite.config.ts, vite.firefox.config.ts
=> :+1: set minimum browser versions

src/content/Root.tsx
=> :bug: Observe frames to unload

src/components/SettingsEditor.tsx, src/content/Root.tsx, src/content/components/ElementInfo.css, src/content/components/ElementInfo.tsx, src/content/components/Tip.css, src/content/components/Tip.tsx, src/content/dom/collectElements.ts, src/content/dom/tips/langTips.test.ts, src/content/dom/tips/langTips.ts, src/content/dom/tips/pageTips.test.ts, src/content/dom/tips/pageTips.ts, src/content/injectRoot.tsx, src/content/types.ts, src/i18n/en.json, src/i18n/ja.json, src/settings/constatns.ts, src/settings/types.ts
=> :+1: Add page and language settings

src/content/components/Tip.css, src/content/components/Tip.tsx, src/content/dom/tips/linkTips.test.ts, src/content/dom/tips/linkTips.ts, src/content/types.ts, src/i18n/en.json, src/i18n/ja.json
=> :+1: add linkTarget tip

manifests/index.ts, src/content/injectRoot.tsx, src/i18n/en.json, src/i18n/ja.json, src/popup/Popup.tsx, src/settings/constatns.ts, src/settings/storage.ts, src/settings/types.ts
=> :+1: Work on local files

src/content/dom/hasInteractiveDescendant.test.ts, src/content/dom/hasInteractiveDescendant.ts, src/content/dom/hasTabIndexDescendant.test.ts, src/content/dom/hasTabIndexDescendant.ts, src/content/dom/tips/buttonTips.test.ts, src/content/dom/tips/buttonTips.ts, src/content/dom/tips/linkTips.test.ts, src/content/dom/tips/linkTips.ts, src/i18n/en.json, src/i18n/ja.json
=> :+1: add error message to nested interactive elements

src/content/dom/isInline.test.ts, src/content/dom/isInline.ts, src/content/dom/tips/buttonTips.test.ts, src/content/dom/tips/buttonTips.ts, src/content/dom/tips/formTips.test.ts, src/content/dom/tips/formTips.ts, src/content/dom/tips/isDefaultSize.test.ts, src/content/dom/tips/isDefaultSize.ts, src/content/dom/tips/linkTips.test.ts, src/content/dom/tips/linkTips.ts, src/i18n/en.json, src/i18n/ja.json, src/types/dom.d.ts
=> :+1: add small target warning

src/background.ts, src/content/index.ts, src/content/injectRoot.tsx
=> :+1: apply enabled/disabled when visibilitychange

src/content/dom/isInline.test.ts, src/content/dom/isInline.ts, src/content/dom/tips/buttonTips.ts, src/content/dom/tips/isSmallTarget.test.ts, src/content/dom/tips/isSmallTarget.ts, src/content/dom/tips/linkTips.ts
=> :sparkles: Adjust small target exeption logic

src/content/dom/isInline.test.ts, src/content/dom/isInline.ts
=> :sparkles: remove next sibling from inline judgement

src/content/dom/tips/isDefaultSize.ts
=> :sparkles: add opacity to target default style judgement

src/content/dom/isInline.test.ts, src/content/dom/isInline.ts
=> :sparkles: add textContent condition of sibling to isInline

package.json, src/content/dom/isHidden.test.ts, src/content/dom/isHidden.ts, src/content/dom/tips/linkTips.test.ts, src/content/dom/tips/linkTips.ts, src/i18n/en.json, src/i18n/ja.json
=> :bug: fix Tips in area element not shown in firefox

src/content/dom/Selectors.ts, src/content/dom/collectElements.test.ts, src/content/hooks/useLiveRegion.ts
=> :+1: support multiple role attributes

src/content/components/ElementInfo.tsx, src/content/dom/Selectors.ts, src/content/dom/getElementCategory.test.ts, src/content/dom/getElementCategory.ts, src/content/types.ts, src/rules/Rules.ts, src/rules/hgroup/index.test.ts, src/rules/hgroup/index.ts
=> :+1: add hgroup

src/content/Root.tsx, src/content/components/Announcements.tsx, src/content/hooks/useLiveRegion.ts, src/test/TestIframe.tsx, src/test/categories/Layout.tsx, src/test/categories/LiveRegion.tsx
=> :bug: Fix double-rendering live regions

docs/ja/UsersGuide.md
from チェク to チェック
Delete a english sentence
=> Fix ja/UsersGuide.md

src/i18n/en.json, src/i18n/ja.json, src/i18n/ko.json, src/rules/aria-state/index.test.ts, src/rules/aria-state/index.ts, src/test/categories/FormControl.tsx
=> :+1: add readonly and required to AriaState

apps/browser_extension/src/i18n/en.json, apps/browser_extension/src/i18n/ja.json, apps/browser_extension/src/i18n/ko.json, apps/browser_extension/src/rules/Rules.ts, apps/browser_extension/src/rules/id-reference/index.test.ts, apps/browser_extension/src/rules/id-reference/index.ts
New Feature: Show missing referenced IDs
=> show errors for missing ids

apps/browser_extension/entrypoints/content/components/ElementInfo.tsx, apps/browser_extension/entrypoints/content/dom/collectElements.ts
- fixed border positions of elements in top layer (popovers or dialogs)
- changed tip position to reflect the scroll position for sections, headings ,tables, and lists
=> Fix display position

apps/browser_extension/src/i18n/en.json, apps/browser_extension/src/i18n/ja.json, apps/browser_extension/src/i18n/ko.json, apps/browser_extension/src/rules/id-reference/index.test.ts, apps/browser_extension/src/rules/id-reference/index.ts, apps/website/src/components/tests/FormControlTests.astro
Changed id-reference rule
- Down the level from error to warning
- Show which attribute has missing IDs
=> Change id reference to warning

apps/browser_extension/src/i18n/en.json, apps/browser_extension/src/i18n/ja.json, apps/browser_extension/src/i18n/ko.json, apps/browser_extension/src/rules/Rules.ts, apps/browser_extension/src/rules/abstract-role/index.test.ts, apps/browser_extension/src/rules/abstract-role/index.ts, apps/browser_extension/src/rules/aria-validation/ariaSpec.ts, apps/browser_extension/src/rules/aria-validation/index.test.ts, apps/browser_extension/src/rules/aria-validation/index.ts
- Remove aria-attribute value format rule
- Show error if using abstract role
=> Revise WAI-ARIA rules

apps/browser_extension/entrypoints/content/components/RuleTip.tsx, apps/browser_extension/entrypoints/content/components/Tip.css, apps/browser_extension/entrypoints/content/dom/Selectors.ts, apps/browser_extension/entrypoints/content/dom/getElementCategory.ts, apps/browser_extension/entrypoints/content/types.ts, apps/browser_extension/src/components/ElementTypeTabs.tsx, apps/browser_extension/src/i18n/en.json, apps/browser_extension/src/i18n/ja.json, apps/browser_extension/src/i18n/ko.json, apps/browser_extension/src/rules/Rules.ts, apps/browser_extension/src/rules/tab-index/index.test.ts, apps/browser_extension/src/rules/tab-index/index.ts, apps/browser_extension/src/rules/type.ts, apps/browser_extension/src/settings/constants.ts, apps/browser_extension/src/settings/presets.ts, apps/browser_extension/src/settings/storage.ts, apps/browser_extension/src/settings/types.ts
- Show tabindex attribute value
- Warn if invalid and positiove values were set
=> add tab-index rule
